name: Python package

on:
  push:
    branches:
    - master

jobs:
  upload:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - name: Upload package
      run: |
        python -m pip install --upgrade pip
        python setup.py upload
